### ISSUE TITLE
[Bug] [Crash] Spawn bug 

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#155]
# Bug Report

## Version info

Zone Version: 1.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> Crash on entity spawn

## How to reproduce?

>> create a zone, hope it natually spawns

### Crash report?

```txt
[15:40:42] [Server thread/ERROR] [sponge]: Could not pass SpawnEntityEvent$Pre$Impl to zones
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at org.zone.region.ZoneManager.getPriorityZone(ZoneManager.java:117) ~[ZoneManager.class:?]
        at org.zone.region.flag.entity.monster.move.MonsterPreventionListener.lambda$onMonsterSpawnEvent$1(MonsterPreventionListener.java:52) ~[MonsterPreventionListener.class:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.zone.region.flag.entity.monster.move.MonsterPreventionListener.onMonsterSpawnEvent(MonsterPreventionListener.java:48) ~[MonsterPreventionListener.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_MonsterPreventionListener_onMonsterSpawnEvent6.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.manager.RegisteredListener.handle(RegisteredListener.java:88) ~[RegisteredListener.class:1.16.5-8.0.0-RC1032]
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:372) ~[SpongeEventManager.class:1.16.5-8.0.0-RC1032]
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:399) ~[SpongeEventManager.class:1.16.5-8.0.0-RC1032]
        at net.minecraft.server.level.ServerLevel.handler$zcd000$tracker$throwPreEventAndRecord(ServerLevel.java:5410) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:830) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:765) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:11) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:283) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:197) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:1161) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.redirect$zcc000$tracker$wrapEntitySpawner(ServerChunkCache.java:1623) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.lambda$tickChunks$5(ServerChunkCache.java:388) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:368) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:337) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:353) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapWorldTick(MinecraftServer.java:4332) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:871) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:312) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapUpdateTimeLightAndEntities(MinecraftServer.java:4314) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:811) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:670) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:257) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]```

**Comment by mosemister** [comment]
This crash is to do with multiple threads attempting to access the same list, typically its also do with a thread writing to the list as well. The error of this isnt to do with the spawning, its just the spawning triggered this code.
