### ISSUE TITLE
[Bug] enabling/disabling player prevention causes crash

### ISSUE THREAD

**Issue by mosemister** [Zone-Protect/Zone-protect#94]
# Bug Report

## Version info

Zone Version: 1.0.0.0
Sponge API: 8.0.0
Sponge impl: Sponge Vanilla
Minecraft version: MC 1.16.5

## Description of bug

>> crash

## How to reproduce?

>> run enable/disable for player prevention

### Crash report?

```txt
ionException: [Flags, zones, preventplayers, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.zone.region.ZoneManager.save(ZoneManager.java:261)
        at org.zone.region.Zone.save(Zone.java:257)
        at org.zone.commands.structure.region.flags.prevention.player.ZoneFlagPreventionPlayerEnableDisableCommand.run(ZoneFlagPreventionPlayerEnableDisableCommand.java:59)
        at org.zone.commands.structure.ZoneSpongeCommand.process(ZoneSpongeCommand.java:111)
        at org.spongepowered.common.command.registrar.SpongeRawCommandRegistrar.process(SpongeRawCommandRegistrar.java:90)
        at org.spongepowered.vanilla.launch.command.VanillaCommandManager.processCommand(VanillaCommandManager.java:46)
        at org.spongepowered.common.command.manager.SpongeCommandManager.process(SpongeCommandManager.java:357)
        at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.execute(SpongeCommandDispatcher.java:126)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:70)
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.execute(DelegatingCommandDispatcher.java:45)
        at net.minecraft.commands.Commands.performCommand(SourceFile:249)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(SourceFile:1211)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1198)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1177)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:36)
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(SourceFile:9)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:263)
        at net.minecraft.network.protocol.PacketUtils.md45a90f$lambda$tracker$redirectProcessPacket$0$0(SourceFile:552)
        at net.minecraft.server.TickTask.run(SourceFile:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:144)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23)
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(SourceFile:4348)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:761)
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:155)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:118)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(SourceFile:743)
        at net.minecraft.server.MinecraftServer.pollTask(SourceFile:737)
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(SourceFile:127)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(SourceFile:722)
        at net.minecraft.server.MinecraftServer.runServer(SourceFile:674)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(SourceFile:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.configurate.serialize.SerializationException: [Flags, zones, preventplayers, Enabled] of type java.util.Optional: No serializer available for type class java.util.Optional
        at org.spongepowered.configurate.ScopedConfigurationNode.set(ScopedConfigurationNode.java:120)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:180)
        at org.spongepowered.configurate.AbstractConfigurationNode.set(AbstractConfigurationNode.java:43)
        at org.zone.region.flag.move.player.preventing.PreventPlayersFlagType.save(PreventPlayersFlagType.java:48)
        at org.zone.region.flag.move.player.preventing.PreventPlayersFlagType.save(PreventPlayersFlagType.java:13)
        at org.zone.region.flag.Flag.save(Flag.java:131)
        at org.zone.region.ZoneManager.save(ZoneManager.java:259)
        ... 31 more
```

**Comment by Lukamon24** [comment]
Hijacked
